global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: kafka-brokers
    static_configs:
      - targets:
          - kafka-1:7071
          - kafka-2:7071
          - kafka-3:7071
        labels:
          cluster: aerostream-local

  - job_name: schema-registry
    metrics_path: /metrics
    static_configs:
      - targets:
          - schema-registry:8081

  - job_name: aerostream-producer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - aerostream-producer:8090
        labels:
          service: producer
          cluster: aerostream-local

  - job_name: kafka-connect
    metrics_path: /metrics
    static_configs:
      - targets:
          - kafka-connect:8083
        labels:
          service: kafka-connect
          cluster: aerostream-local

  - job_name: aerostream-stream-processor
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - aerostream-stream-processor:8091
        labels:
          service: stream-processor
          cluster: aerostream-local

  - job_name: aerostream-ml-consumer
    metrics_path: /metrics
    static_configs:
      - targets:
          - aerostream-ml-consumer:8099
        labels:
          service: ml-consumer
          cluster: aerostream-local
